### ISSUE TITLE
Изменение в своём коде меняет код всех загруженных миров кодинга

### ISSUE THREAD

**Issue by G0LES** [justmc-community/JustMC#11]
### Игровой никнейм

_Goles_ (Найдено DominosMersi)

### Ожидаемое поведение

Код одного игрока не влияет код другого игрока

### Наблюдаемое/фактическое поведение

При установке/поломке блока кодинг меняется во всех мирах. Установили блок в одном мире -> он установится во всех загруженных кодингах игрока.
Тоже самое с поломкой. Сломали в одном мире -> сломали данный блок во всех мирах. (Так можно гриферить)

### Пошаговое воспроизведение проблемы

Нужно 2 игрока (или больше)

1. Первый игрок в своём кодинге, другой(ие) в чужом.
2. Первый игрок ставит блок -> у второго (других) игрока(ов) магическим образом ставится блок.
3. Аналогично с поломкой.

### Дополнительная информация

[Перенесено с гитлаба]
Выбор действия на табличке, установка предмета в сундук никак не влияет на чужой кодинг. (Сундук не появляется, табличка тоже)
Возможно этот баг связан с недавним обновлением, где изменено сохранение кода.

**Comment by andreypfau** [comment]
fixed
