### ISSUE TITLE
Баг с триггером игрока "Правый Клик"

### ISSUE THREAD

**Issue by yWeJlecm** [justmc-community/JustMC#111]
### Игровой никнейм

_XMater500X_

### Ожидаемое поведение

По нажатию на ПКМ произойдёт перевод в режим Наблюдатель.

### Наблюдаемое/фактическое поведение

Перевод в режим Наблюдатель происходит только тогда, когда игрок смотрит на блок, который в радиусе использования. (У такого блока появляется обводка).

### Пошаговое воспроизведение проблемы

1. Войти в свой мир.
2. Перейти в режим /dev.
3. В режиме /dev сделать цепочку кода {Триггер игрока: "Правый клик", Действие игрока: "Режим игры: Наблюдатель"}.
4. Перейти в режим /play.
5. В режиме /play нажать ПКМ, смотря в воздух, на далёкий блок, на ближний блок.

**Comment by FreshL1me** [comment]
Это не баг, событие работает, если игрок кликает по любому блоку ИЛИ держит предмет в руке

**Comment by yWeJlecm** [comment]
> Это не баг, событие работает, если игрок кликает по любому блоку ИЛИ держит пред

**Comment by yWeJlecm** [comment]
> 
> 
> Это не баг, событие работает, если игрок кликает по любому блоку ИЛИ держит предмет в руке

Работать должно впринципе, если ты нажимаешь ПКМ, вне зависимости от того, на что ты смотришь.

**Comment by andreypfau** [comment]
fixed
