### ISSUE TITLE
Добыча креатива на спавне при помощи бумажек с местоположением

### ISSUE THREAD

**Issue by G0LES** [justmc-community/JustMC#12]
### Игровой никнейм

_Goles_

### Ожидаемое поведение

Ничего, из бумажка никак не влияет на перемещение на спавн.

### Наблюдаемое/фактическое поведение

Можно добыть креатив на спавне при помощи бумажки с местоположением, ниже опишу пошагово как делать. (2 способа)

### Пошаговое воспроизведение проблемы

Способ 1:

1. В кодинге нажать F на бумажку, переместится в ваш мир.
2. Умереть в мире (при помощи пустоты)
3. Вы появитесь на спавне, и кое-какое время будете иметь креатив.

Способ 2:

1. В кодинге нажать F на бумажку, переместится в ваш мир.
2. Написать /gamemode 3
3. Телепортироватся к человеку, который стоит на спавне.
4. Написать /gamemode 1.

### Дополнительная информация

[Перенесено с гитлаба]
Со временем у вас отберут креатив, но всё равно что-то успеете выкинуть на спавн.
Если что команды /gamemode продолжают работать на спавне. Возможно ещё какие-то команды, но я не тестил.

**Comment by andreypfau** [comment]
fixed
