### ISSUE TITLE
Баг с "Удалить предметы"

### ISSUE THREAD

**Issue by yWeJlecm** [justmc-community/JustMC#139]
### Игровой никнейм

_XMaster500X_

### Ожидаемое поведение

При смерти из инвентаря удалятся нужные мне предметы.

### Наблюдаемое/фактическое поведение

При смерти из инвентаря выпало всё содержимое, включая предметы, которые должны были удалиться. Сами предметы удалились в контейнере кода.
То есть вместо того, чтобы удалить предметы у меня, код удалил их из сундука.

### Пошаговое воспроизведение проблемы

1. Сделать цепочку кода {Триггер: "Смерть игрока", Действие над игроком: "Удалить предметы:64 камня"}
2. Сделать цепочку кода {Триггер: "Вход игрока", Действие над игроком: "Выдать предметы: 19 камня, любые дополнительные предметы"}
3. Перейти в режим /play
4. Умереть, упав с высоты
5. Перейти в режим /dev
6. Посмотреть на содержимое сундука "Удалить предметы".

**Comment by zingeer** [comment]
fixed

**Comment by zingeer** [comment]
fixed
