### ISSUE TITLE
Мивочка пе...Действие над мобом работает на игрока

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#140]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

тестил неделю назад

### Наблюдаемое/фактическое поведение

Что я стал невидимкой и неуязвимым

### Пошаговое воспроизведение проблемы

https://disk.yandex.ru/i/1hNZm0shCGi6MA
видео

**Comment by MiWO4kaA** [comment]
Что такое "Мивочка пе...", к чему тут это вообще, я абсолютно не понимаю ход твоих глупых бессмысленных мыслей, ты должен объяснить  в заголовке главное, но ты написал "Мивочка пе..." ну пе, и что, это глупо, повзрослей уже немного, может ты хотел сделать что то смешное, пошутить, но тут находят баги, тут считай идёт вся разработка сервера, разработчику не до смеху, я считаю это несмешным и глупым, такие люди не должны иметь уважения в свою сторону из за таких глупых "смешков",  "клоунада", не более, теперь всё, я высказал всё своё мнение которое считал нужным, будет лучше если такого больше не повториться.

**Comment by Firch** [comment]
> Ожидаемое поведение
> 
> тестил неделю назад
> 

?????

**Comment by andreypfau** [comment]
Отклонено, не по форме
