### ISSUE TITLE
Если "игрок смотрит на блок" не учитывает тип блока

### ISSUE THREAD

**Issue by xiaC4ll** [justmc-community/JustMC#145]
### Игровой никнейм

Kamidan

### Ожидаемое поведение

Если "игрок смотрит на блок" учитывает координаты и тип блока, который я положил в него. 

### Наблюдаемое/фактическое поведение

Если "игрок смотрит на блок" учитывает только координаты блока.

### Пошаговое воспроизведение проблемы

1. Создаём простенькую цепочку
![ 03_16_46_21_Minecraft_1 17 1_-_Multiplayer_(3rd-party_Server)javaw](https://user-images.githubusercontent.com/42979061/140082726-cc10fe07-b5d9-4056-9117-61b98abd7f59.png)
![ 03_16_46_48_Minecraft_1 17 1_-_Multiplayer_(3rd-party_Server)javaw](https://user-images.githubusercontent.com/42979061/140082809-8c0770ea-594a-4947-a5c6-cb33f8233175.png)
![ 03_16_47_12_Minecraft_1 17 1_-_Multiplayer_(3rd-party_Server)javaw](https://user-images.githubusercontent.com/42979061/140082865-d90fca37-4b3f-4bf8-8787-5785804edaa6.png)
2. Кликаем по блоку на этих координатах в мире
![ 03_16_47_59_Minecraft_1 17 1_-_Multiplayer_(3rd-party_Server)javaw](https://user-images.githubusercontent.com/42979061/140082994-7e531f31-e0f7-4bf9-8d8c-5b00e4e1df5d.png)

**Comment by zingeer** [comment]
Всё работает корректно, ты проверяешь или тип блока или местоположение. Для того чтобы проверить тип блока на локации используйте блок если игра и там блок равен.
