### ISSUE TITLE
Мировой чат не отображается в /dev

### ISSUE THREAD

**Issue by Amaiqwef** [justmc-community/JustMC#146]
### Игровой никнейм

lemonhead2000

### Ожидаемое поведение

Чат в режиме /build или /play отображается в режиме /dev

### Наблюдаемое/фактическое поведение

Чат не отображается

### Пошаговое воспроизведение проблемы

Зайти в /dev и попросить кого-нибудь написать в чат в режиме /play или /build

**Comment by yWeJlecm** [comment]
Он и не должен отображаться.

**Comment by Amaiqwef** [comment]
Как не должен. А если я в код зашёл, а мне хотят что-то написать. Чат в мире должен быть локальный, общий между режимами.

**Comment by yWeJlecm** [comment]
> 
> 
> Как не должен. А если я в код зашёл, а мне хотят что-то написать. Чат в мире должен быть локальный, общий между режимами.

Да, согласен. Но это не баг. Поэтому ты можешь предложить это в идеях.

**Comment by Amaiqwef** [comment]
> > Как не должен. А если я в код зашёл, а мне хотят что-то написать. Чат в мире должен быть локальный, общий между режимами.
> 
> Да, согласен. Но это не баг. Поэтому ты можешь предложить это в идеях.

Идея - это не всегда то, что будет на сервере. Идея может так и остаться идея.
А баг - это когда так не должно быть, поэтому всё норм

**Comment by yWeJlecm** [comment]
> 
> 
> > > Как не должен. А если я в код зашёл, а мне хотят что-то написать. Чат в мире должен быть локальный, общий между режимами.
> > 
> > 
> > Да, согласен. Но это не баг. Поэтому ты можешь предложить это в идеях.
> 
> Идея - это не всегда то, что будет на сервере. Идея может так и остаться идеей. А баг - это когда так не должно быть, поэтому всё норм

Значит, по твоей логике, всё, что по моему мнению, так не должно быть - баг? На самом деле нет, это не так. Раз ты подал именно идею, значит пиши её в идеях, а не багах.

**Comment by realDosed** [comment]
Как это может быть не багом, если это явный баг

**Comment by andreypfau** [comment]
Это действительно баг

**Comment by yWeJlecm** [comment]
> 
> 
> Это действительно баг

Ну, если ты уже пытался это реализовать, и это не работает, тогда это баг. А если ты ещё не начинал это реализовывать, то идея.

**Comment by zingeer** [comment]
fixed
