### ISSUE TITLE
В компасе не нажимается на "Выдать полёт/строительство"

### ISSUE THREAD

**Issue by Amaiqwef** [justmc-community/JustMC#149]
### Игровой никнейм

lemonhead2000

### Ожидаемое поведение

В компасе можно нажать на "выдать полёт/строительство"

### Наблюдаемое/фактическое поведение

В компасе нельзя нажать на "выдать полёт/строительство"

### Пошаговое воспроизведение проблемы

https://user-images.githubusercontent.com/45568969/140181015-75467d94-0509-441d-87cd-9c168eee817e.mp4

### Дополнительная информация

У меня всё работает. У полимера почему-то нет

**Comment by zingeer** [comment]
fixed
