### ISSUE TITLE
Странно работает изменение имени мира

### ISSUE THREAD

**Issue by Amaiqwef** [justmc-community/JustMC#150]
### Игровой никнейм

lemonhead2000

### Ожидаемое поведение

Неожидал, что выведет "Имя мира успешно изменено"

### Наблюдаемое/фактическое поведение

Выводит, при том даже не в мире, но при этом название самого мира не меняет

### Пошаговое воспроизведение проблемы

https://user-images.githubusercontent.com/45568969/140182029-19446b34-3c2d-4c5c-8246-08f4dd8da68c.mp4

### Дополнительная информация

Также нужно добавить возможность отмены (может быть /cancel или что-то такое - можно сделать это универсальной командой, которую можно будет использовать для отмены еще чего-нибудь)

**Comment by zingeer** [comment]
fixed
