### ISSUE TITLE
Авторизация по Discord не работает...

### ISSUE THREAD

**Issue by Geo3gamer** [justmc-community/JustMC#151]
### Игровой никнейм

sliva_ru

### Ожидаемое поведение

Сервер привяжется к моему аккаунту в Discord, и аккаунт в Minecraft пройдёт авторизацию.

### Наблюдаемое/фактическое поведение

При привязке аккаунта выдаётся ошибка
![изображение](https://user-images.githubusercontent.com/47525358/140294854-768f35ac-2141-436b-b147-7f84f30315a2.png)

### Пошаговое воспроизведение проблемы

Авторизоваться через Discord

### Дополнительная информация

Фронт загружается со второго раза как в Firefox (94.0), так и в Microsoft Edge (95.0.1020.40)

**Comment by andreypfau** [comment]
@Geo3gamer попробуй сейчас, была опечатка в ссылке редиректа.

А по поводу что фронт грузится с второго раза это приколы последствия ддос атаки, защита какая то активировалась видимо

**Comment by Geo3gamer** [comment]
После редиректа на JustMC ничего не происходит, просто пустая страница

**Comment by andreypfau** [comment]
ага вижу, щас поправим...

**Comment by andreypfau** [comment]
@Geo3gamer а сейчас?

**Comment by Geo3gamer** [comment]
@andreypfau всё так же пустая страница в FF

**Comment by andreypfau** [comment]
@Geo3gamer сейчас добавил побольше логирования, зайди еще раз, увижу в чем проблема

**Comment by andreypfau** [comment]
@Geo3gamer пробуй

**Comment by Geo3gamer** [comment]
@andreypfau ничего не изменилось

**Comment by andreypfau** [comment]
@Geo3gamer еще раз

**Comment by Geo3gamer** [comment]
@andreypfau опять не работает

**Comment by andreypfau** [comment]
@Geo3gamer и финальный раз... надеюсь

**Comment by Geo3gamer** [comment]
@andreypfau да, всё работает.

**Comment by andreypfau** [comment]
Отлично, пофиксили
