### ISSUE TITLE
Фантомный мир

### ISSUE THREAD

**Issue by Amaiqwef** [justmc-community/JustMC#156]
### Игровой никнейм

lemonhead2000

### Ожидаемое поведение

Мир запускается снова

### Наблюдаемое/фактическое поведение

https://user-images.githubusercontent.com/45568969/140378015-b434de8a-d7d0-47e7-a1f4-51c492e5c3e7.mp4

### Пошаговое воспроизведение проблемы

1. Любой игрок входит в ваш мир
2. Вы открываете меню миров
3. Игрок выходит, а мир остаётся
4. Тыкаем на свой мир
5. Результат на видео (при этом моего мира вообще нет в списках миров)

**Comment by zingeer** [comment]
больше не повторялась
