### ISSUE TITLE
Не можешь ставить блоки в билде и в плее потомучто игрок в другом мире или у тебя в коде

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#16]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Что я поставлю блок или сломаю

### Наблюдаемое/фактическое поведение

Не ставится и не ломается

### Пошаговое воспроизведение проблемы

Вход в мир и поставить блок или сломать

### Дополнительная информация

Игрок в коде в своем мире и когда другой игрок в своем мире в билде и в плее блоки не ставяться и не ломаются
И уменя появилась ещё версия если игрок в коде а другой игрок в своем мире можно приготовить площадку для кода и кодить

**Comment by G0LES** [comment]
Если что видео было на старом гитлабе (если нужно будет, как я понял проблема одна и та же): https://gitlab.com/justmc/justmc/-/issues/371

**Comment by zingeer** [comment]
Баг больше не наблюдается.
