### ISSUE TITLE
Голосовать за миры можно только один раз

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#163]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Можно голосовать за разные миры

### Наблюдаемое/фактическое поведение

Если проголосовать за один мир и попытаться проголосовать за другой мир, то появится ошибка
![изображение](https://user-images.githubusercontent.com/92986692/140572609-04d59465-1d7a-4074-97bc-ed7380092e77.png)

### Пошаговое воспроизведение проблемы

Зайти в чей-то мир, написать /vote
Зайти в другой мир и снова написать /vote

**Comment by yWeJlecm** [comment]
Я точно знаю, что такого бага нет. Много раз голосовал за разные миры и ничего. Скорее всего, ты уже проголосовал за этот мир. Там надо долго ждать.

**Comment by yWeJlecm** [comment]
Баг работае впринципе, если имеется задержка по голсованию на какой-либо мир.

**Comment by zingeer** [comment]
Такой баг есть

**Comment by yWeJlecm** [comment]
> 
> 
> Такой баг есть

Ммм, ну да? А кто-то против?
