### ISSUE TITLE
Если существо имя равно не работает

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#165]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Должно работать

### Наблюдаемое/фактическое поведение

Не работает

### Пошаговое воспроизведение проблемы

Триггер существа (получает урон): Если существо имя равно (<указать UUID/имя>) -> отправить ВСЕМ сообщение

**Comment by zingeer** [comment]
всё работает
