### ISSUE TITLE
Вещи для кодинга не возвращаются

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#166]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Когда возвращаюсь в dev через листочек с местоположением, то мне в инвентарь должны возвращаться предметы для кодинга

### Наблюдаемое/фактическое поведение

Из инвентаря пропадают все предметы для кодинга, кроме местоположения и не возвращаются, пока снова не написать /dev

### Пошаговое воспроизведение проблемы

Взять листочек местоположение в кодинге, 2 раза нажать F

**Comment by zingeer** [comment]
fixed
