### ISSUE TITLE
Ломание и установление блоков в коде без взаймодействия владельца мира

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#17]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Точто я буду хорошо кодить

### Наблюдаемое/фактическое поведение

Блоки ломаются магическим образом

### Пошаговое воспроизведение проблемы

Вход в код и другой игрок в коде своем ломает блоки и ломаются они тоже
Также с установлением блоков

### Дополнительная информация

На таблички и сундуки не работает

**Comment by andreypfau** [comment]
Дубликат https://github.com/justmc-community/JustMC/issues/11
