### ISSUE TITLE
Нормальный телепорт для листочка кода

### ISSUE THREAD

**Issue by andreypfau** [justmc-community/JustMC#182]
### Discussed in https://github.com/justmc-community/JustMC/discussions/181

<div type='discussions-op-text'>

<sup>Originally posted by **MiWO4kaA** November 11, 2021</sup>
Сделать чтоб листочек кода телепортировал на точку спавна мира а не куда то не непонятные координаты, тоесть когда нажимаешь на f тебя должно телепортировать в обычном мире на месте спавна игроков</div>

**Comment by TheSirCororo** [comment]
Баг , видимо, был пофикшен, не смог воспроизвести (создал новый мир, проверил телепортацию и телепортирует на спавн мира (в центр))
