### ISSUE TITLE
Недоработка в меню управления миром

### ISSUE THREAD

**Issue by yWeJlecm** [justmc-community/JustMC#186]
### Игровой никнейм

_XMaster500X_

### Ожидаемое поведение

При закрытии/открытии входа в мир будет меняться иконка мира в меню управления миром (с барьера на дёрн и наоборот).

### Наблюдаемое/фактическое поведение

При закрытии/открытии входа в мир иконка меняется только при новом открытии меню управления миром.

### Пошаговое воспроизведение проблемы

1. Закрыть вход в мир
2. Открыть вход в мир

**Comment by TheSirCororo** [comment]
fixed
