### ISSUE TITLE
Не работает "Если игрок одет в предмет"

### ISSUE THREAD

**Issue by SrGzuck19** [justmc-community/JustMC#187]
### Игровой никнейм

SrGzuck19_

### Ожидаемое поведение

Отмена атаки с её дальнейшим уроном если на игроке одет предмет "Алмазный блок", чтобы не сработал тригер "Игрок получил урон"

### Наблюдаемое/фактическое поведение

Если игрок c алмазным блоком на голове ударяет другого игрока урон не проходит, но тригер "Игрок получил урон" Срабатывает.

### Пошаговое воспроизведение проблемы

![Screenshot_8](https://user-images.githubusercontent.com/94184312/141489089-82ea28ce-c0de-4e4c-af94-26e035181721.png)

(На табличке есть слово "Атакующий" без неё происходит тоже самое.)

**Comment by TheSirCororo** [comment]
Это не работает только с маркером "Любой" или "Все" или во всех случаях?

**Comment by SrGzuck19** [comment]
> Это не работает только с маркером "Любой" или "Все" или во всех случаях?

Во всех.

**Comment by andreypfau** [comment]
fixed
