### ISSUE TITLE
Не обновляется количество голосов за мир в меню онлайн

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#189]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Голоса под миром изменятся моментально

### Наблюдаемое/фактическое поведение

Должно пройти некоторое время, чтобы голоса за мир обновились

### Пошаговое воспроизведение проблемы

Зайти в любой мир (до этого приметить сколько было голосов), написать /vote, выйти на спавн и посмотреть, что количество голосов не изменилось

**Comment by zingeer** [comment]
fixed
