### ISSUE TITLE
Событие игрока "Нажал правой кнопкой мыши" работает некорректно

### ISSUE THREAD

**Issue by gedashu** [justmc-community/JustMC#191]
# Описание
В /play событие игрока "Нажал правой кнопкой мыши" работает некорректно, при правом нажатии мышки происходит два раза, если держать ничего, но если держать любой предмет, то работает как один раз.

Если кликать по воздуху (не по блоку), то ничего не происходит.

Смотреть прикреплённое видео.
# Видео
https://user-images.githubusercontent.com/46973251/141652983-d3eb5160-4f62-404f-bee2-8411b10e65af.mp4

**Comment by zingeer** [comment]
дубликат
