### ISSUE TITLE
Проблема с действием над миром "установить предметы в контейнер", нельзя выставлять предметы и местоположение

### ISSUE THREAD

**Issue by MiWO4kaA** [justmc-community/JustMC#195]
### Игровой никнейм

MiWO4kaA_

### Ожидаемое поведение

Если выбрать в действие над миром установить предметы в контейнере можно будет выбрать местоположение и предмет который требуется установить.

### Наблюдаемое/фактическое поведение

При выборе вышесказанного сундук куда можно положить местоположение и предмет не появиться.

### Пошаговое воспроизведение проблемы

1. Зайти в код, /dev
2. Поставить действие над миром
3. Выбрать "Установить предметы в контейнере"

### Дополнительная информация

![image](https://user-images.githubusercontent.com/80840061/141856931-6c169170-2359-4b72-a48b-b663e01c37ad.png)
Вот скриншот, в описании написано что можно выбрать предметы и местоположение, исходя с него я решил зарепортить. Может быть что это ошибка перевода, либо я чего то не понял, извините если сделал что то неправильно.

**Comment by zingeer** [comment]
fixed
