### ISSUE TITLE
Визер не телепортируется.

### ISSUE THREAD

**Issue by SrGzuck19** [justmc-community/JustMC#196]
### Игровой никнейм

SrGzuck19_

### Ожидаемое поведение

Телепорт Визера при "Если сущность находится рядом", "Если сущность является мобом","Действие над сущностью телепортация"

### Наблюдаемое/фактическое поведение

Действия проходят, Визер не телепортируется. 

### Пошаговое воспроизведение проблемы

![Screenshot_3](https://user-images.githubusercontent.com/94184312/141954915-36268082-2bef-43cf-90fb-d2cc53474a5e.png)

**Comment by SrGzuck19** [comment]
> у меня всё работает... Я использовал = Моб получается урон - если является мобом - телепортация

Значит проблема в "если сущность находится рядом".

**Comment by zingeer** [comment]
ну это уже другой баг
