### ISSUE TITLE
Установить блоки в регионе

### ISSUE THREAD

**Issue by olfesre** [justmc-community/JustMC#218]
### Игровой никнейм

OLFESRE

### Ожидаемое поведение

Вставил нужные параметры - заработало

### Наблюдаемое/фактическое поведение

![](https://i.gyazo.com/217323af3ca71cbdbf117c1dd42fb645.png)

### Пошаговое воспроизведение проблемы

![](https://i.gyazo.com/29498e5207e84cfe3bea97c18290609f.png)
![](https://i.gyazo.com/a034d56fdb454e6f6f58f31d5e1a69e1.png)
Блок снега, координата одного угла и противоположного угла мира (127, 3, 127 / -127, 3, -127), с помощью инструмента "Местоположение" из переменных.

**Comment by FreshL1me** [comment]
Это действие отключено, потому что из-за него потом в мире появляются дыры

**Comment by andreypfau** [comment]
fixed
