### ISSUE TITLE
Мир иногда откатывается когда я перезахожу

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#28]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Ничего просто зайду и пойду мир делать

### Наблюдаемое/фактическое поведение

Часть которую я сетнул кодом осталась сетнулось несколько блоков только
Также с шалкером я положил предметы в шалкер и они пропали

### Пошаговое воспроизведение проблемы

Нету

**Comment by andreypfau** [comment]
fixed
