### ISSUE TITLE
Работает любой компас в режиме строителя

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#29]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Просто нажму пкм и ничего не случиться

### Наблюдаемое/фактическое поведение

Открылось гуи с настройками мира

### Пошаговое воспроизведение проблемы

Взять компас > пкм > всё

**Comment by zingeer** [comment]
Не работает, проверил.
