### ISSUE TITLE
Некоторые строки кода не работают с функцией ждать

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#30]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Что строчка кода сработает удачно

### Наблюдаемое/фактическое поведение

Ничего не произошло либо произошло но не сразу

### Пошаговое воспроизведение проблемы

Нету

### Дополнительная информация

Я вам напишу 1 пример
Пкм>держит предмет>ждать 1 тик>телепортировать
если же сделать без ждать может не телепортировать

**Comment by zingeer** [comment]
всё работает
