### ISSUE TITLE
Баг с исполнением кода

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#40]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Код должен работать для всех

### Наблюдаемое/фактическое поведение

Код не работает на меня, но на других работает

### Пошаговое воспроизведение проблемы

Зайти в /dev (независимо от того, мир в режиме игры или строительства), взять местоположение и нажать F, написать /play
Код не будет работать для меня, пока я не перезапущу мир (т.е. перезаход не помогает)

**Comment by zingeer** [comment]
Не работает уже
