### ISSUE TITLE
If variable text matches повторяется в меню два раза

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#42]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

В меню проверка If variable text matches должна быть одна

### Наблюдаемое/фактическое поведение

Их двое, и отличаются они тем, что в одном есть маркер для включения\выключения регулярных выражений, а в другом нет
![изображение](https://user-images.githubusercontent.com/92986692/138572396-800e6fd4-8c5f-4e96-a0a6-4ef11c9d6d13.png)
![изображение](https://user-images.githubusercontent.com/92986692/138572401-a4ab929b-e81d-42e4-94b1-852b579cc168.png)

### Пошаговое воспроизведение проблемы

Зайти в код и открыть меню блока Если переменная

**Comment by zingeer** [comment]
fixed
