### ISSUE TITLE
Проверка "Текст начинается с" повторяется в меню два раза

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#43]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

Проверка "Текст начинается с" в меню только одна

### Наблюдаемое/фактическое поведение

Их 2, причем у второй странный аргумент (он только один и это переменная)
![изображение](https://user-images.githubusercontent.com/92986692/138572483-4411bedc-e693-46fc-8658-eba2313c0d64.png)
![изображение](https://user-images.githubusercontent.com/92986692/138572490-2ca790a8-913a-42be-9454-b1acf9c864b6.png)

### Пошаговое воспроизведение проблемы

Зайти в код и открыть меню блока Если переменная

**Comment by zingeer** [comment]
fixed
