### ISSUE TITLE
Instant respawn работает только со смертью из-за игроков\мобов

### ISSUE THREAD

**Issue by FreshL1me** [justmc-community/JustMC#45]
### Игровой никнейм

FreshLime_

### Ожидаемое поведение

При любой смерти будет моментальное возрождение 

### Наблюдаемое/фактическое поведение

Моментальное возрождение будет, если причиной смерти был игрок\существо

### Пошаговое воспроизведение проблемы

Вход: set Instant respawn  (true)
Умереть в бездне

**Comment by zingeer** [comment]
fixed
