### ISSUE TITLE
Выдача строительства не работает и влияет на тпс

### ISSUE THREAD

**Issue by Firch** [justmc-community/JustMC#64]
### Игровой никнейм

Firchex

### Ожидаемое поведение

Нажимаю на кирпичный блок и появляется меню доступа к билду

### Наблюдаемое/фактическое поведение

Он не реагирует и сбрасывается на нач позицию - при этом залагивает тпс

### Пошаговое воспроизведение проблемы

1. Зайти в компасс
2. Не нажимается

### Дополнительная информация

Перезаход из мира и даже с сервера не фиксит

**Comment by zingeer** [comment]
видео мне с багом дайте, у меня не воспроизводится...
