### ISSUE TITLE
При >1 действий "Установить регион" первое действие не срабатывает

### ISSUE THREAD

**Issue by White-145** [justmc-community/JustMC#69]
### Игровой никнейм

White_145Gaming

### Ожидаемое поведение

Все действия работают нормально

### Наблюдаемое/фактическое поведение

Работают все действия кроме первого
![image](https://user-images.githubusercontent.com/74352995/138881676-da324bc4-fbe1-40fa-a7a7-d4f2739818b1.png)
![image](https://user-images.githubusercontent.com/74352995/138881699-586f9f08-b904-42a4-a1e7-6a3a4cb11943.png)

### Пошаговое воспроизведение проблемы

Поставить триггер (для примера: "Прыжок")
Поставить 2-3 действия "Установить регион" подряд
Запустить мир и прыгнуть
...
...
Все действия сработали кроме первого

### Дополнительная информация

Когда написано "действия" я имею в виду именно действия "Установить регион"

**Comment by andreypfau** [comment]
fixed
