### ISSUE TITLE
Нельзя ставить и ломать блоки в своём мире

### ISSUE THREAD

**Issue by hardwareSpaceman** [justmc-community/JustMC#7]
### Игровой никнейм

realDosed

### Ожидаемое поведение

При установке или ломании блока в режиме строительства эти действия должны выполняться.

### Наблюдаемое/фактическое поведение

Нельзя установить или сломать блоки в мире.

### Пошаговое воспроизведение проблемы

Создать мир и попробовать поставить или сломать любой блок.

**Comment by andreypfau** [comment]
Это только сегодня появилось или как давно?

**Comment by MiWO4kaA** [comment]
> Это только сегодня появилось или как давно?

Нет уже было

**Comment by andreypfau** [comment]
fixed
