### ISSUE TITLE
Переменные не записывают местоположение а сохраняют лишь местоположение игрока

### ISSUE THREAD

**Issue by DominosMersi5776** [justmc-community/JustMC#72]
### Игровой никнейм

Dominowka

### Ожидаемое поведение

Что все будет

### Наблюдаемое/фактическое поведение

Ничего не случилось телепортировался на месте

### Пошаговое воспроизведение проблемы

Пкм>присв переменную местоположение взгляда

**Comment by zingeer** [comment]
У вас день на видео, или я закрываю баг
