### ISSUE TITLE
Триггер "если игрок нажимает пкм" работает неправильно

### ISSUE THREAD

**Issue by yyyaaa1** [justmc-community/JustMC#94]
### Игровой никнейм

yyyaaa

### Ожидаемое поведение

Срабатывание при нажатии пкм

### Наблюдаемое/фактическое поведение

Триггер срабатывает только если игрок нажимает пкм по блоку

### Пошаговое воспроизведение проблемы

Поставить триггер игрока "если нажимает пкм" и любое действие.

При переходе в режим игры триггер сработает только если нажимать на блок.

**Comment by andreypfau** [comment]
fixed
